FROM public.ecr.aws/lambda/java:21

COPY transaction-processor/target/classes ${LAMBDA_TASK_ROOT}

COPY transaction-processor/target/dependency/* ${LAMBDA_TASK_ROOT}/lib/

CMD ["com.flowops.transactionprocessor.consumer.TransactionProcessorLambdaHandler::handleRequest"]